// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import "./libs/shim/urijs.js";
import papaparse from "./libs/papaparse.js";
import { group,sleep } from "k6";

export let options = {
  maxRedirects: 1,
  noVUConnectionReuse: true,
  vus: 1,
  ext: {
    loadimpact: {
      projectID: 3630700,
      // Test runs with the same name groups test runs together
      name: "ORDER LOAD"
    }
  }
};

const file = (() => {
  // Load data file
  const text = open("./data.csv");
  const rows = papaparse.parse(text, { header: true }).data;
  return rows;
})();
options.iterations = file.length;

const Iteration = Symbol.for("iteration");
const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  environment: {
    pincode: "560075",
    latitude: "",
    longitude: "",
    url: "https://st-ciago.furlenco.com",
    ghost_token: "",
    "x-panem-token": "",
    userId: "",
    cartID: "",
    deliveryAddressID: "",
    paymentID: "",
    paymentAmount: "",
    orderID: "",
    cartCheckOutID: "",
    orderDisplayID: "",
    personelID: "",
    "x-gatekeeper-token": "",
    citiID: "1",
    mozart: "https://st-mozart.furlenco.com",
    fortknox: "https://st-fortknox.furlenco.com",
    LMS_URL: "https://st-lms-api.furlenco.com",
    random_cap: "",
    phoneNumber2: "",
    productID_1: "17",
    productID_2: "122",
    productID_3: "110",
    productID_4: "107",
    productID_5: "116",
    productID_6: "101",
    productID_7: "23",
    productID_8: "35",
    productID_9: "113",
    productID_10: "20",
    productID_11: "29"
  },
  data: file
});

export default function () {
  postman[Iteration]();

  group("create-user-order", function () {
    postman[Request]({
      name: "0.0 Meta",
      id: "0e5cedb5-1fd0-4a91-b67b-ff876f2e5c11",
      method: "GET",
      address: "{{url}}/api/v1/meta",
      headers: {
        "x-city-id": "{{citiID}}",
        "x-pincode": "{{pincode}}",
        "x-panem-token": ""
      },
      pre() {
        
      },
      post(response) {
        var jsonData = JSON.parse(responseBody);
        postman.setEnvironmentVariable(
          "ghost_token",
          jsonData.data.meta.ghost_user.ghost_identifier
        );
        pm.test("Status code is 200", function () {
          pm.response.to.have.status(200);
          console.log("0.0 Meta : ✅ ")
        });
      }
    });

    postman[Request]({
      name: "0.1 - Login",
      id: "3917322a-4005-4faf-9296-2e38819926d6",
      method: "POST",
      address: "{{url}}/api/v1/users/verify-account",
      data: '{\n  "account": "{{phoneNumber2}}"\n}',
      headers: {
        accept: "application/json",
        "Content-Type": "application/json",
        "x-ghost-identifier": "{{ghost_token}}",
        "x-panem-token": ""
      },
      pre() {
        const randomNumber = Math.floor(Math.random() * 900000000) + 100000000;
        const phoneNumber = "9" + randomNumber.toString();
        postman.setEnvironmentVariable("phoneNumber2", phoneNumber);
      },
      post(response) {
        pm.test("Status code is 200", function () {
          pm.response.to.have.status(200);
          console.log("0.1 - Login : ✅ ")
        });
      }
    });

    postman[Request]({
      name: "0.2 otp",
      id: "595b9fc7-b8dc-407e-a232-d34eea77686c",
      method: "POST",
      address: "{{url}}/api/v1/users/verify-otp",
      data: '{\n  "account": "{{phoneNumber2}}",\n  "otp": "1234"\n}',
      headers: {
        accept: "application/json",
        "Content-Type": "application/json",
        "x-ghost-identifier": "{{ghost_token}}",
        "x-panem-token": ""
      },
      pre() {
      },
      post(response) {
        pm.test("Status code is 200", function () {
          pm.response.to.have.status(200);
          console.log("0.2 otp : ✅ ")
        });
      }
    });

    postman[Request]({
      name: "0.3 register",
      id: "5bc4de3f-ce04-479a-b07e-db31119b3f8e",
      method: "POST",
      address: "{{url}}/api/v1/users/register",
      data:
        '{\n  "contact_no": "{{phoneNumber2}}",\n  "email_id": "destroyer_san5-{{phoneNumber2}}@furlenco.com",\n  "name": "destroyer_san5-{{$randomFirstName}}"\n}',
      headers: {
        accept: "application/json",
        "Content-Type": "application/json",
        "x-ghost-identifier": "{{ghost_token}}",
        "x-panem-token": ""
      },
      pre() {
      },
      post(response) {
        var jsonData = JSON.parse(responseBody);
        postman.setEnvironmentVariable(
          "x-panem-token",
          jsonData.data.user.session_token.token
        );
        postman.setEnvironmentVariable("userId", jsonData.data.user.id);
        pm.test("Status code is 200", function () {
          pm.response.to.have.status(200);
          console.log("0.3 register : ✅ ")
        });
      }
    });

    postman[Request]({
      name: "1. get-cart",
      id: "1999c982-9f08-480c-9d09-c3d1d871466d",
      method: "GET",
      address: "{{url}}/api/v1/carts?cityId={{citiID}}&pincode={{pincode}}",
      headers: {
        "x-panem-token": "{{x-panem-token}}"
      },
      post(response) {
        var jsonData = JSON.parse(responseBody);
        postman.setEnvironmentVariable("cartID", jsonData.data.cart.id);
        pm.test("Status code is 200", function () {
          pm.response.to.have.status(200);
          console.log("1. get-cart : ✅ ")
        });
      }
    });

    postman[Request]({
      name: "2. add-item",
      id: "e37b8d55-6576-4900-bbb2-43fed2272c54",
      method: "POST",
      address:
        "{{mozart}}/furlenco-checkout/api/carts/{{cartID}}/bulkCartItems?pincode={{pincode}}&cityId={{citiID}}",
      data:
        '[\n  {\n     "id": {{productID_1}},\n     "tenure":12\n  },\n  {\n     "id": {{productID_2}},\n     "tenure":12\n  },\n  {\n     "id": {{productID_3}},\n     "tenure":12\n  },\n  {\n     "id": {{productID_4}},\n     "tenure":12\n  },\n  {\n     "id": {{productID_5}},\n     "tenure":12\n  },\n  {\n     "id": {{productID_6}},\n     "tenure":12\n  },\n  {\n     "id": {{productID_7}},\n     "tenure":12\n  },\n  {\n     "id": {{productID_8}},\n     "tenure":12\n  },\n  {\n     "id": {{productID_9}},\n     "tenure":12\n  },\n  {\n     "id": {{productID_10}},\n     "tenure":12\n  },\n  {\n     "id": {{productID_11}},\n     "tenure":12\n  }\n]',
      headers: {
        "x-panem-token": "{{x-panem-token}}",
        "Content-Type": "application/json"
      },
      post(response) {
        pm.test("Status code is 200", function () {
          pm.response.to.have.status(200);
          console.log("2. add-item : ✅ ")
        });
      }
    });

    postman[Request]({
      name: "3. add-address",
      id: "189ab90e-8f96-4bcd-80e2-9e66991cdfd9",
      method: "POST",
      address: "{{url}}/api/v1/users/addresses",
      data:
        '{\n     "name": "HOK-HEAD",\n    "line1": "HOK",\n    "line2": "HOK",\n    "line3": "HOK",\n    "address":"HOK-TECH",\n    "contact_no": "{{phoneNumber2}}",\n    "city_name": "HOK CITY",\n    "pincode": "{{pincode}}",\n    "latitude": {{latitude}},\n    "longitude": {{longitude}},\n    "email_id": "destroyer-sanil@gmail.com",\n    "city_id": {{citiID}},\n    "floor": 4,\n    "service_lift_available": false,\n    "accommodation_type":"independent_house"\n}',
      headers: {
        "x-panem-token": "{{x-panem-token}}",
        "Content-Type": "application/json"
      },
      post(response) {
        var jsonData = JSON.parse(responseBody);
        postman.setEnvironmentVariable(
          "deliveryAddressID",
          jsonData.data.deliveryAddress.id
        );
        pm.test("Status code is 200", function () {
          pm.response.to.have.status(200);
          console.log("3. add-address : ✅ ")
        });
      }
    });

    postman[Request]({
      name: "4. add-address-to-cart",
      id: "5521b1f5-af61-4458-acb2-5be7da7ff081",
      method: "PUT",
      address:
        "{{url}}/api/v1/carts/{{cartID}}?cityId={{citiID}}&pincode={{pincode}}",
      data:
        '{\n  "billingAddressId": {{deliveryAddressID}},\n  "shippingAddressId": {{deliveryAddressID}},\n  "activeCart": "ALL"\n}',
      headers: {
        "x-panem-token": "{{x-panem-token}}",
        "Content-Type": "application/json"
      },
      post(response) {
        pm.test("Status code is 200", function () {
          pm.response.to.have.status(200);
          console.log("4. add-address-to-cart : ✅ ")
        });
      }
    });
    postman[Request]({
      name: "5. createPayment",
      id: "dddf20ab-7ae5-4eba-90ff-14a4af9dd5e5",
      method: "POST",
      address:
        "{{url}}/api/v1/carts/{{cartID}}/createPayment?cityId={{citiID}}&pincode={{pincode}}",
      data: '{\n    "gstin": ""\n}',
      headers: {
        "x-panem-token": "{{x-panem-token}}"
      },
      post(response) {
        pm.test("Status code is 200", function () {
          pm.response.to.have.status(200);
          console.log("5. createPayment : ✅ ")
        });

        var jsonData = JSON.parse(responseBody);
        postman.setEnvironmentVariable(
          "paymentID",
          jsonData.data.paymentDetails.id
        );
        postman.setEnvironmentVariable(
          "paymentAmount",
          jsonData.data.paymentDetails.amount
        );
      }
    });
    console.log(" 😴  😴  for 2 second for Checkout process : ")
    sleep(2);

    postman[Request]({
      name: "6. create-checkout-order",
      id: "713a213c-9b1e-4f4a-bf98-8b344827549b",
      method: "POST",
      address:
        "{{url}}/api/v1/carts/{{cartID}}/create-checkout-order?cityId={{citiID}}&pincode={{pincode}}",
      headers: {
        "x-panem-token": "{{x-panem-token}}"
      },
      post(response) {
        pm.test("Status code is 200", function () {
          pm.response.to.have.status(200);
          console.log("6. create-checkout-orde : ✅ ")
        });

        var jsonData = JSON.parse(responseBody);
        postman.setEnvironmentVariable(
          "orderID",
          jsonData.data.order.orders[0].id
        );
        postman.setEnvironmentVariable(
          "cartCheckOutID",
          jsonData.data.order.id
        );
        postman.setEnvironmentVariable(
          "orderDisplayID",
          jsonData.data.order.orders[0].displayId
        );
      }
    });
    console.log(" 😴  😴  for 2 second for payment process : ")
    sleep(2);

    postman[Request]({
      name: "7. Payment",
      id: "3cbbd19e-58b0-4f8b-9c3d-35e6d9b910a6",
      method: "POST",
      address: "{{fortknox}}/debug/send-message/GRINGOTTS__PAYMENT_UPDATES",
      data:
        '{\n  "status": "COMPLETED",\n  "userActionType": "CART_CHECKOUT",\n  "publisherUUID": "{{$randomUUID}}",\n  "id": "{{paymentID}}",\n  "paid": {\n    "totalAmount": "{{paymentAmount}}",\n    "paymentOffers": [\n      {\n        "type": "NCEMI",\n        "amount": "717.01"\n      }\n    ],\n    "paymentInstruments": {\n      "CASH": "{{paymentAmount}}",\n      "FCASH": "0.00"\n    }\n  },\n  "paymentDetails": {\n    "id": "{{paymentID}}}"\n  }\n}\n',
      headers: {
        "Content-Type": "application/json"
      },
      post(response) {
        pm.test("Status code is 200", function () {
          pm.response.to.have.status(200);
          console.log("7. Payment : ✅ ")
        });
      }
    });
    console.log(" 😴  😴  for 2 second for KYC process : ")
    sleep(2);

    postman[Request]({
      name: "8.KYC",
      id: "4464e1cb-cb17-485f-922c-5d0d30b360e7",
      method: "POST",
      address: "{{fortknox}}/debug/send-message/DELPHI__KYC_UPDATES",
      data:
        '{\n    "kycState": "APPROVED",\n    "userId": {{userId}},\n    "publisherUUID": "{{$randomUUID}}",\n    "orderId": "{{orderID}}"\n}',
      headers: {
        "Content-Type": "application/json"
      },
      post(response) {
        pm.test("Status code is 200", function () {
          pm.response.to.have.status(200);
          console.log("8.KYC : ✅ ")
        });
      }
    });

    postman[Request]({
      name: "logout",
      id: "fea3595d-b14a-4727-a876-85f70e365864",
      method: "DELETE",
      address: "https://st-ciago.furlenco.com/api/v1/users/logout",
      headers: {
        "x-panem-token": "{{x-panem-token}}",
        "x-city-id": "{{citiID}}",
        "x-pincode": "{{pincode}}"
      },
      post(response) {
        pm.test("Status code is 200", function () {
          pm.response.to.have.status(200);
          pm.environment.set("x-panem-token", "");
          console.log("9 .Logout : ✅ ")
        });
      }
    });
  });
  console.log("- - - - 🎯 🎯 🎯 🎯 🎯 🎯 🎯 🎯 🎯 🎯 - - - -")
}
